name: 🔁 Notify Sweep (daily)

on:
  schedule:
    # ── Daily sweep ────────────────────────────────────────────────────────────────
    # Runs once per day at 03:00 UTC (no DST).
    # Fires at: 03:00 every day (UTC).
    # Tip: if you want to stagger with other jobs, change the minute (e.g. "17 3 * * *").
    - cron: "0 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: notify-all
  cancel-in-progress: true

jobs:
  call-notify-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Call notify endpoint (tier=daily)
        shell: bash
        env:
          BASE_URL: ${{ secrets.BACKEND_BASE_URL }}    
          PATH_PART: ${{ secrets.NOTIFY_PATH }}        
          HDR_NAME: ${{ secrets.INTERNAL_HEADER_NAME }}
          HDR_VALUE: ${{ secrets.INTERNAL_API_KEY }}   
        run: |
          set -euo pipefail
          URL="${BASE_URL%/}${PATH_PART}"
          curl -sSf -X POST "$URL" \
            -H "content-type: application/json" \
            -H "$HDR_NAME: $HDR_VALUE" \
            --data '{"tier":"daily"}'
